<?php

/**
 * Implements hook_block_info().
 */
function testimonial_block_info() {
  $blocks['testimonials'] = array(
    'info' => t('Testimonials Sidebar'),
    'cache' => DRUPAL_NO_CACHE
  );
  $blocks['testimonials_content'] = array(
    'info' => t('Testimonials Content'),
    'cache' => DRUPAL_NO_CACHE,
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function testimonial_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'testimonials':
    	if(arg(0) == 'node' && is_numeric(arg(1))){
    		$node = node_view(node_load(arg(1)),'testimonial');
    		if(isset($node['field_testimonials'][0])){
    			$block['subject'] = t('Testimonials');
    			if(isset($node['field_testimonial_title'][0]['#markup'])){
    				$block['subject'] = t($node['field_testimonial_title'][0]['#markup']);
    			}
    			$block['content'] = $node['field_testimonials'];
    		}
		}
		break;
    case 'testimonials_content':
        if ($node = menu_get_object()){
            $node = node_view($node, 'testimonial');
            if(isset($node['field_testimonials'][0])){
                $block['subject'] = t('Testimonials');
                if(isset($node['field_testimonial_title'][0]['#markup'])){
                    $block['subject'] = t($node['field_testimonial_title'][0]['#markup']);
                }
                hide($node['field_testimonial_title']);
                $block['content'] = $node;
            }
        }
    break;
  }
  return $block;
}

/**
 * Implements hook_node_view().
 */
function testimonial_node_view($node, $view_mode, $langcode) {
  if($node->type == 'testimonial'){
  	$node->content['body'][0]['#markup'] = '"'.$node->content['body'][0]['#markup'].'"';
  	$node->content['field_persons_name'][0]['#markup'] = '- '.$node->content['field_persons_name'][0]['#markup'];
  }
}

/**
 * Implements hook_entity_info_alter().
 */
function testimonial_entity_info_alter(&$entity_info) {
    $entity_info['node']['view modes']['testimonial'] = array(
        'label' => t('Testimonial'),
        'custom settings' => TRUE,
    );
}