<?php

/**
 * @file
 * This module blocks users from accidentally submitting a form twice. The
 * protection only comes from jQuery and is not server side, so this is only
 * effective against accidentaly clicking of the button by users with Javascript
 * enabled (which is a very high percent of users).
 */

/**
 * Adds the settings.
 *
 * @return
 *   TRUE if hide_submit is active.
 */
function hide_submit_add_settings($form, &$form_state) {
  static $hide_submit_settings;
  if (!$hide_submit_settings) {
    $hide_submit_settings = array('hide_submit' => array(
      'hide_submit_status' => TRUE,
      'hide_submit_method' => variable_get('hide_submit_method', 'disable'),
      'hide_submit_css' => variable_get('hide_submit_css', 'hide-submit-disable'),
      'hide_submit_abtext' => t(variable_get('hide_submit_abtext', '')),
      'hide_submit_atext' => t(variable_get('hide_submit_atext', '')),
      'hide_submit_hide_css' => variable_get('hide_submit_hide_css', 'hide-submit-processing'),
      'hide_submit_hide_text' => t(variable_get('hide_submit_hide_text', 'Processing...')),
      'hide_submit_hide_fx' => t(variable_get('hide_submit_hide_fx', FALSE)),
      'hide_submit_reset_time' => (int)variable_get('hide_submit_reset_time', 5000),
    ));
  }

  drupal_add_js($hide_submit_settings, 'setting');

  return $form;
}

/**
 * Implements hook_form_alter().
 */
function hide_submit_form_alter(&$form, &$form_state, $form_id) {
  if(in_array($form_id, hide_submit_valid_forms())) {
    // Add javascript.
    if (!isset($form['#attached']['js'])) {
      $form['#attached']['js'] = array();
    }
    $form['#attached']['js'][drupal_get_path('module', 'hide_submit') . '/hide_submit.js'] = array(
      'type' => 'file',
      'weight' => 10,
    );

    // Add css.
    if (!isset($form['#attached']['css'])) {
      $form['#attached']['css'] = array();
    }
    $form['#attached']['css'][drupal_get_path('module', 'hide_submit') . '/hide_submit.css'] = array(
      'type' => 'file',
      'weight' => 10,
    );

    $form['#after_build'][] = 'hide_submit_add_settings';
  }
}

function hide_submit_valid_forms(){
  return module_invoke_all('hide_submit_valid_forms');
}

/**
 * Implements hook_menu().
 */
function hide_submit_menu() {
  $items = array();

  $items['admin/config/content/hide-submit'] = array(
    'title' => 'Hide submit settings',
    'description' => 'Configure the hiding of the form submit button.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('hide_submit_settings'),
    'access arguments' => array('administer site configuration'),
    'file' => 'hide_submit.admin.inc',
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}
