<?php

/**
 * Implements hook_menu().
 */
function promo_menu() {
  $items['admin/ytu-settings/promo'] = array(
    'title' => 'Promo Settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('promo_admin_setting_form'),
    'access arguments' => array('access ytu settings'),
    'file' => 'promo.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_init().
 */
function promo_init() {
	if(variable_get('promo_enable', 0)){
		$promo_id = variable_get('promo_id', '');
		if(!promo_saw_promo($promo_id)){
			drupal_add_js(drupal_get_path('module', 'promo').'/promo.js');
			drupal_add_js(array('promo' => 
				array('content' => '<div id="promo-popup"><div id="promo-close"><img src="/'.drupal_get_path('theme','yogatuneup').'/images/ico-close.png" alt="close" /></div>'.variable_get('promo_content', '').'</div>')
			),'setting');
			promo_set_as_seen($promo_id);
		}
	}
}

function promo_saw_promo($promo_id){
	return isset($_COOKIE['Drupal_visitor_first_visit_'.$promo_id]) || (isset($_SESSION) && isset($_SESSION['saw_promo_'.$promo_id]));
}

function promo_set_as_seen($promo_id){
	user_cookie_save(array('first_visit_'.$promo_id => 1));
	$_SESSION['saw_promo_'.$promo_id] = TRUE;
}