<?php

/**
 * Implements hook_menu().
 */
function faq_menu() {
  $items['faqs'] = array(
    'title' => 'FAQs',
    'page callback' => 'faq_page_callback',
    'access arguments' => array('access content'),
  );

  return $items;
}

/**
 * Implements hook_node_view().
 */
function faq_node_view($node, $view_mode, $langcode) {
  if($node->type == 'faq'){
  }
}

function faq_page_callback(){
	return theme('faq_listings',array('categories' => faq_get_faqs_by_category()));
}

/**
 * Implements hook_theme().
 */
function faq_theme($existing, $type, $theme, $path) {
  return array(
    'faq_listings' => array(
      'template' => 'faq-listings',
      'variables' => array('categories' => array()),
    ),
  );
}

function faq_get_faqs_by_category(){
	$categories = array();

	$query = db_select('node','n')
			->fields('n',array('nid'))
			->condition('n.type','faq')
			->condition('n.status',1);
	$query->innerJoin('field_data_field_faq_category','fc','n.nid = fc.entity_id');
	$query->innerJoin('taxonomy_term_data','ttd','fc.field_faq_category_tid = ttd.tid');
	$query->innerJoin('nodequeue_nodes','nn','n.nid = nn.nid');
	$query->fields('ttd',array('name'))->orderBy('ttd.weight')->orderBy('ttd.name')->orderBy('nn.position');

	$result = $query->execute();
	foreach($result as $row){
		$categories[$row->name][] = node_view(node_load($row->nid));
	}

	return $categories;
}